version: "3.7"
services:
  scraperpg:
    container_name: ${CONTAINER_NAME:-scraperpg}
    image: postgres:11
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: scraper
    networks:
        - scraper-network
    ports:
        - "5432:5432"
    volumes:
        - ../data/db:/data/db
  backend:
    build: .
    depends_on:
      - scraperpg
    ports:
      - "9000:9000"
    networks:
      - scraper-network
networks:
  scraper-network:
    name: scraper-network
    driver: bridge